name: Android Testing Workflow

on:
  push:
    branches: 
      - release/*
  pull_request:
    branches: 
      - develop
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

    # Step 2: Decode Google services configuration file
    - name: Decode google-services.json
      env:
       FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_CONFIG > app/google-services.json

    # Step 3: Check the code with ktlint, you can remove this job if you don't use ktlint
    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck

    # Step 3: Check the code with Android linter
    - name: Run Android Linter
      run: ./gradlew lintStagingDebug

    # Step 4: Yun your unit tests
    - name: Run Unit Tests
      run: ./gradlew testStagingDebugUnitTest
